### ISSUE TITLE
参加考试了，考试合格，等待后台审核的时候，需要给出相应的提示，不能总是提示没参加认证

### ISSUE THREAD

**Issue by laye0619** [laye0619/SAC#4]
<img width="618" alt="screen shot 2018-02-03 at 11 08 42 am" src="https://user-images.githubusercontent.com/9484313/35762527-bb16ea60-08d2-11e8-9980-fdc6c2845d74.png">

**Comment by joyzhaop** [comment]
参加完考试的提示已经完成：
1.等待审核
![image](https://user-images.githubusercontent.com/36144562/35788654-a0caadfe-0a71-11e8-85db-da8419f3d388.png)
2.审核未通过
![image](https://user-images.githubusercontent.com/36144562/35788747-43bf72ba-0a72-11e8-9c57-91f738510031.png)

**Comment by laye0619** [comment]
Close it。
