### ISSUE TITLE
后台->公司管理->点击同意就卡住

### ISSUE THREAD

**Issue by laye0619** [laye0619/SAC#5]
<img width="1033" alt="screen shot 2018-02-03 at 12 27 47 pm" src="https://user-images.githubusercontent.com/9484313/35763012-ab6adb34-08dd-11e8-840c-6353b9f75f94.png">

**Comment by joyzhaop** [comment]
修改完成并测试通过，目前已经无卡顿问题
![image](https://user-images.githubusercontent.com/36144562/35788996-04065d9e-0a74-11e8-9064-8d4927bad759.png)

**Comment by laye0619** [comment]
Done
